apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: '359a3d8ac2d6ba8ff347a30d39e1509fcccecf8f'
  - name: appGitUrl
    value: 'git@github.com:ajaygupta1999/coffee-testing.git'
  - name: configGitUrl
    value: 'git@github.com:ajaygupta1999/coffee-testing-config.git'
  - name: appImage
    value: 'registry.hub.docker.com/ajaygupta1999/coffee-shop'
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---