apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: '993dee1c508aa3c1130f4347252708e9bc5283fb'
  - name: appGitUrl
    value: 'git@github.com:ajaygupta1999/coffee-testing.git'
  - name: configGitUrl
    value: 'git@github.com:ajaygupta1999/coffee-testing-config.git'
  - name: appImage
    value: 'registry.hub.docker.com/ajaygupta1999/coffee-shop'
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---
