apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-deploy
  serviceAccountName: pipeline
  params:
  - name: buildRevision
    value: '59d500522d10c23601c510ce9681221b08782282'
  - name: appGitUrl
    value: 'git@github.com:ajaygupta1999/coffee-testing.git'
  - name: configGitUrl
    value: 'git@github.com:ajaygupta1999/coffee-testing-config.git'
  - name: appImage
    value: 'docker.ajaygupta1999.com/coffee-testing'
  workspaces:
  - name: app-source
    emptyDir: {}
  - name: config-source
    emptyDir: {}
---
