kind: Service
apiVersion: v1
metadata:
  name: barista
spec:
  selector:
    app: barista
  ports:
  - port: 8080
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista
      version: v1
  template:
    metadata:
      labels:
        app: barista
        version: v1
      annotations:
        revision: "f9674341c1fcce92a06be21cc950c1210827de72"
    spec:
      containers:
      - name: barista
        image: sdaschner/barista:quarkus-testing-1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
      restartPolicy: Always
---