apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: coffee-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "acd29bfbd75044ea9818d81917d5ded1-767195423.us-west-1.elb.amazonaws.com"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-gateway
spec:
  hosts:
  - "acd29bfbd75044ea9818d81917d5ded1-767195423.us-west-1.elb.amazonaws.com"
  gateways:
  - coffee-gateway
  http:
  - match:
    - uri:
        prefix: "/processes"
    route:
    - destination:
        host: barista.production.svc.cluster.local
        subset: v1
        port:
          number: 8080
  - match:
    - uri:
        prefix: "/orders"
    - uri:
        prefix: "/types"
    - uri:
        prefix: "/health"
    route:
    - destination:
        host: coffee-shop.production.svc.cluster.local
        subset: v1
        port:
          number: 8080
---


