kind: Service
apiVersion: v1
metadata:
  name: barista
spec:
  selector:
    app: barista
  ports:
  - port: 8080
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista
      version: v1
  template:
    metadata:
      labels:
        app: barista
        version: v1
      annotations:
        revision: "e288a4038a586e2134b7e602cd15022a6de44718"
    spec:
      containers:
      - name: barista
        image: rodolpheche/wiremock:2.6.0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
---