apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-gateway-2
  namespace: istio-system
spec:
  hosts:
  - "coffeeshop.testing.com"
  gateways:
  - coffee-gateway
  http:
  - match:
    - uri:
        prefix: "/processes"
    - uri:
        prefix: "/__admin"
    route:
    - destination:
        host: barista.systemtest.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: "/orders"
    - uri:
        prefix: "/types"
    - uri:
        prefix: "/health"
    - uri:
        prefix: "/index.html" 
    - uri:
        prefix: "/order.html"
    - uri:
        prefix: "/form.js"
    - uri:
        prefix: "/style.css"
    - uri:
        prefix: "/types"
    - uri:
        prefix: "/types/espresso/origins"
    - uri:
        prefix: "/types/pour_over/origins"
    - uri:
        prefix: "/types/latte/origins"         
    route:
    - destination:
        host: coffee-shop.systemtest.svc.cluster.local
        port:
          number: 8080
---
