apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-gateway-2
  namespace: istio-system
spec:
  hosts:
  - "coffeeshop.testing.com"
  gateways:
  - coffee-gateway
  http:
    route:
    - destination:
        host: coffee-shop.systemtest.svc.cluster.local
        port:
          number: 8080
---
