apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coffee-gateway
  namespace: default
spec:
  ingressClassName: kong
  rules:
  - host: systemtest.coffe-shop.com
    http:
      paths:
      - path: /processes
        pathType: Prefix
        backend:
          service:
            name: barista
            port:
              number: 8080
      - path: /__admin
        pathType: Prefix
        backend:
          service:
            name: barista
            port:
              number: 8080
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: coffee-shop
            port:
              number: 8080
      - path: /types
        pathType: Prefix
        backend:
          service:
            name: coffee-shop
            port:
              number: 8080
      - path: /q/health
        pathType: Prefix
        backend:
          service:
            name: coffee-shop
            port:
              number: 8080
---      


